# find_package(gtest QUIET)
enable_testing()
# if(GTEST_LIBRARY)
#     message("GTEST INCLUDE DIR: ${GTEST_INCLUDE_DIRS}")
#     include_directories(${GTEST_INCLUDE_DIRS})
# else()
#     message("gtest library not found !!! setting it up at link target")
#     set(GTEST_LIBRARY gtest)
# endif()

file(GLOB_RECURSE test_SOURCES
  RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/tests/cpp-unittests "*utest.cpp")

foreach(test_exec ${test_SOURCES})
    message("add : ${test_exec}")
    string(REGEX REPLACE "\\.[^.]*$" "" test_name ${test_exec})
    add_executable(${test_name} tests/cpp-unittests/${test_exec})
    target_link_libraries(${test_name} ${GTEST_LIBRARY} ${PROJECT_NAME})
    include(GoogleTest)
    gtest_add_tests(TARGET ${test_name})
endforeach()
