enable_testing()
include_directories(${GTEST_INCLUDE_DIRS})
add_executable(atomic_operators_utest tests/atomic_operators_utest.cpp)
target_link_libraries(atomic_operators_utest gtest ${PROJECT_NAME})
include(GoogleTest)
gtest_add_tests(TARGET atomic_operators_utest)
